### PR TITLE
perf(access-log): initialize IntlDateFormatter once based on i…

### PR DESCRIPTION
**Pull request by pistej**
…cu format instead of slow static StrftimeToICUFormatMap::mapStrftimeToICU()

Test inspired from php.net: https://onlinephp.io/c/bd25a

### CODE REVIEW

**Comment by pistej** [comment]
@Rastusik PR should be ready, thx ...also I can  find some spare time, so if u have some tasks, ideas u want to implement can look into it :)

**Review by Rastusik — APPROVED** [review]

**Comment by Rastusik** [comment]
@pistej yeah, all done, thank you for the contribution ;) ... regarding new features, I have some in mind but they aren't easy, so not sure if you'd like to play with them :)

**Comment by Rastusik** [comment]
@pistej how about your coordinator experiments?

**Comment by pistej** [comment]
@Rastusik didint look at cooridinator, since then, ... since hooks are still experimental (or?), not enabled, coordinator is not needed since execution code is synchronous https://github.com/symfony-swoole/swoole-bundle/pull/107#issuecomment-2040350867

**Pull request merged**
